### ISSUE TITLE
error in add user config

### ISSUE THREAD

**Issue by miladmeidanshahi** [SonyaCore/V2RayGen#36]
```
root@proxy05:~# python3 XRayAgent.py

__   _______                                      _   
\ \ / /  __ \               /\                   | |  
 \ V /| |__) |__ _ _   _   /  \   __ _  ___ _ __ | |_ 
  > < |  _  // _` | | | | / /\ \ / _` |/ _ \ '_ \| __|
 / . \| | \ \ (_| | |_| |/ ____ \ (_| |  __/ | | | |_ 
/_/ \_\_|  \_\__,_|\__, /_/    \_\__, |\___|_| |_|\__|
                    __/ |         __/ |               
                   |___/         |___/                


Loaded Config : config.json
Docker Compose : ON
IP : 164.90.189.7
Protocol : vmess
PORT : 443

XRayAgent.py [options]
    USER Management :
    add, adduser                             Add user
    update, updateuser                       Update existing user
    del, deluser                             Delete existing user
    users, listusers                         List of users

    IPTables :
    deliptables, deleteiptables              Delete rules on server-side port
    climit , conlimit                        Add IP limitations on server-side port

    p, port                                  Change server side port
    h, help                                  Get help
    v, version                               Get version
    q, quit                                  Exit program

cmd > : add
! ADDING User
! Leave Sections Empty for Random Value
Email :a@a.com
ID / UUID : tj2ptj2;t3
AlterID 0 to 64 : 1
ADD user success! uuid: tj2ptj2;t3, alterId: 1, email : a@a.com
Traceback (most recent call last):
  File "/root/XRayAgent.py", line 772, in <module>
    commands["adduser"]()
  File "/root/XRayAgent.py", line 535, in create_user
    link_generator(data, -1)
  File "/root/XRayAgent.py", line 435, in link_generator
    security = data["inbounds"][0]["security"]
KeyError: 'security'
root@proxy05:~# 

```

**Comment by SonyaCore** [comment]
fixed in the latest version
